import { useState } from 'react';

const DEFAULT_BACKGROUNDS = [{ name: 'Default Purple', value: '#120024' }, { name: 'Solid Black', value: '#000000' }, { name: 'Classic White', value: '#ffffff' }];

export default function SettingsPage({ user, activeBg, purchasedBgs, onSelectBackground, onSignOut }) {
  const [previewBg, setPreviewBg] = useState(null);
  const backgrounds = [...DEFAULT_BACKGROUNDS, ...purchasedBgs.filter((value) => !DEFAULT_BACKGROUNDS.some((background) => background.value === value)).map((value, index) => ({ name: `Custom Background ${index + 1}`, value }))];
  const apply = (value) => { onSelectBackground(value); setPreviewBg(null); };
  return <section className="settings-full-page"><div className="page-heading"><h2>⚙️ Account & Application Settings</h2><p className="subtext">Customize your theme and manage account details.</p></div><section className="settings-section"><h3>🎨 Backgrounds & Appearance</h3><p>Preview and switch between default colors or purchased backgrounds.</p><div className="bg-selection-grid">{backgrounds.map((background) => <article className={`bg-card ${activeBg === background.value ? 'active-bg' : ''}`} key={background.value}><div className="bg-preview-box" style={{ background: background.value.startsWith('animated-') ? 'linear-gradient(-45deg, #0d001a, #001233)' : background.value }}><span>{background.name}</span></div><div className="bg-card-info"><span>{activeBg === background.value ? 'Applied' : background.name}</span><div className="bg-actions"><button type="button" onClick={() => setPreviewBg(background.value)}>Preview</button><button type="button" className="apply-btn" disabled={activeBg === background.value} onClick={() => apply(background.value)}>{activeBg === background.value ? 'Applied' : 'Apply'}</button></div></div></article>)}</div></section>{previewBg && <div className="preview-modal-overlay"><div className="preview-modal-card" style={{ background: previewBg.startsWith('animated-') ? 'linear-gradient(-45deg, #0d001a, #001233)' : previewBg }}><h3>Background Preview</h3><p>This is how your workspace background will look.</p><div className="preview-modal-actions"><button type="button" className="apply-btn" onClick={() => apply(previewBg)}>Apply This Background</button><button type="button" className="cancel-btn" onClick={() => setPreviewBg(null)}>Close Preview</button></div></div></div>}<section className="settings-section danger-zone"><h3>👤 Account Actions</h3><div className="account-info-box"><p>Logged in as: <strong>{user.username}</strong></p><button type="button" className="signout-btn-large" onClick={onSignOut}>🚪 Sign Out of Nebula</button></div></section></section>;
}